export enum ActionType {
    SET_CHAIN = "SET_CHAIN",
    SHOW_MODAL = "SHOW_MODAL",
    ADD_LOG = "ADD_LOG",
    ADD_LOGS = "ADD_LOGS",
    SET_SNIPED_TOKENS = "SET_SNIPING_STATS",
    SET_SOLD_TOKENS = "SET_SOLD_TOKENS",
    SET_PROFIT_AMOUNT = "SET_PROFIT_AMOUNT",
    SET_BALANCE = "SET_BALANCE",
    SET_ADDRESS = "SET_ADDRESS",
    SET_PK = "SET_PK",
    SET_TRADE_STATUS = "SET_TRADE_STATUS",
    SET_TRADE_AMOUNT = "SET_TRADE_AMOUNT",
    SET_MIN_BALANCE = "SET_MIN_BALANCE",
    SET_BALANCE_READABLE = "SET_BALANCE_READABLE",
    SET_WITHDRAW_AMOUNT = "SET_WITHDRAW_AMOUNT",
    SET_FIRST_RECEIVER = "SET_FIRST_RECEIVER",
    SET_SECOND_RECEIVER = "SET_SECOND_RECEIVER"
}